documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'docs/**'

github-files:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

dependencies:
  - changed-files:
    - any-glob-to-any-file: 'dependencies/**'

pyroclastic:
  - changed-files:
    - any-glob-to-any-file: 'python/**'

lava-core:
  - changed-files:
    - any-glob-to-any-file: 'tools/**'
