
LAVA_C_FILES := $(shell find . -name '*.c')
.PHONY: lava_preprocess
lava_preprocess: $(LAVA_C_FILES)
	for lavafile in $^; do \
   		$(CC) -include stdio.h $(CFLAGS) -E $${lavafile} -o $${lavafile}_pre; \
		cp $${lavafile} $${lavafile}.bak; \
		mv $${lavafile}_pre $${lavafile}; \
	done