CREATE TABLE t0 (id, x);
INSERT INTO t0(id, x) VALUES (-1E0,'0(o');
INSERT INTO t0(x) VALUES('HELLO WORLD');
INSERT INTO t0(x) VALUES('AAAA BBBB');
INSeRT INTO t0(x) VALUES('CCCC');
SELECT x FROM t0 WHERE x like 'AAAA%';
