CREATE VIRTUAL TABLE t0 USING fts4(x,order=DESC);
INSERT INTO t0(docid,x) VALUES (-1E0,'0(o');
INSERT INTO t0 VALUES('HELLO WORLD');
INSERT INTO t0 VALUES('AAAA BBBB');
INSeRT INTO t0 VALUES('CCCC');
SELECT docid FROM t0 WHERE t0 MATCH'"AAAA*"';
