name: LAVA Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

# Automatically cancel any previous workflow on new push.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test_debian_package:
    if: github.repository == 'panda-re/lava'
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:  
      - name: Checkout LAVA at current commit
        uses: actions/checkout@v6
      
      - name: Install compile dependencies
        run: |
          version=$(lsb_release -rs)
          dep_base=./dependencies/ubuntu_${version}_base.txt
          sudo apt-get -qq update
          if [ -f "${dep_base}" ]; then
            sudo apt-get -y install --no-install-recommends $(cat ${dep_base} | grep -o '^[^#]*')
          else
            echo "Unsupported Ubuntu version: $version. Create a list of base/build dependencies and try again."
            exit 1
          fi

      - name: Create Debian Package
        run: |
          cmake -B"./tools/build" \
          -H"./tools" \
          -DCMAKE_INSTALL_PREFIX="/usr" \
          -DCMAKE_BUILD_TYPE=Release
          cmake --build "./tools/build" --parallel "$(nproc)" --config Release
          cd ./tools/build
          cpack -G DEB
          sudo apt-get install ./lava*.deb

      - name: Create Wheel file
        run: |
          python3 -m pip install --upgrade build
          python3 -m pip install pytest protobuf>=4.21.0
          python3 -m build --wheel .
          python3 -m pip install dist/*.whl

      - name: Quick Python Test
        run: |
          lava-init --no-download
          pytest python
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION : 'python'

  test_install_script:
    if: github.repository == 'panda-re/lava'
    runs-on: ubuntu-22.04
    env:
      PYTHONUNBUFFERED: "1"
      DEBIAN_FRONTEND: noninteractive
      USER: ${{ github.actor }}
      # https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespostgres
          POSTGRES_DB: toy_${{ env.USER }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${POSTGRES_USER}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Update and install all requirements
      run: |
        bash install.sh
        python3 -m pip install --upgrade pip
        python3 -m pip install .
    - name: Setup LAVA
      run: |
        chmod +x ./scripts/*
        lava-init -a
    - name: Add Postgres credentials and Run LAVA
      run: |
        echo "localhost:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}" > ~/.pgpass
        chmod 600 ~/.pgpass
        # Adding Queries
        python -m pyroclastic.lava -q toy
        # Making Binary to run in PANDA
        python -m pyroclastic.lava -m toy
        # Run taint with PANDA (Note sometimes you just need to re-run). Note -c also initializes the database...
        python -m pyroclastic.lava -tc toy
        # Run injection step for various kinds of bugs
        python -m pyroclastic.lava -i 1 toy --bugtypes "ptr_add"
        python -m pyroclastic.lava -i 1 toy --bugtypes "ret_buffer"
        # Alas, for toy, we only have 1 malloc, so injection works, but verification its hard to get the right file...
        # python -m pyroclastic.lava -i 1 toy --bugtypes "malloc_off_by_one"
        # Alas, for REL_WRITE toy is too small for 3 DUAs.
        # Alas, for PRINTF, I genuinely am not sure how it works, plus not a priority
        # Alas, for HEAP_CONST is likely not going to work because we are using modern heaps...
        # python -m pyroclastic.lava -i 1 toy --bugtypes "chaff_stack_unused"
        # python -m pyroclastic.lava -i 1 toy --bugtypes "chaff_stack_const"
        # python -m pyroclastic.lava -i 1 toy --bugtypes "chaff_divzero"

      env:
        USER: ${{ github.actor }}
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgrespostgres

  build_container:
    if: github.repository == 'panda-re/lava'
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v4
        with:
          username: pandare
          password: ${{secrets.ALL_PANDARE_DOCKERHUB}}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: latest
          driver-opts: |
            network=host
          buildkitd-config-inline: |
            [registry."${{ secrets.PANDA_ARC_REGISTRY }}"]
              insecure = true
              http = true

      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ${{ github.workspace }}
          push: true
          tags: |
            pandare/lava:test
